import { auth, signOut } from "@/auth";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from './components/Header';

async function SignOut() {
  "use server"
  await signOut({ redirectTo: "/login" })
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex justify-between items-center px-6 py-4 border-b">

          <Header title="Pocket Flow" ></Header>

          {(session?.user?.transactionGroup?.length ?? 0) > 0 && (
            <select>
              {session?.user.transactionGroup.map((group) => (
                <option key={group.id} value={group.id}>
                  {group.name}
                </option>
              ))}
            </select>
          )}
          {session ? (
            <form action={SignOut}>
              <button className="text-sm text-red-500 hover:text-red-300">logout</button>
            </form>) : null
          }
        </div>
        {children}
      </body>
    </html>
  );
}
